# This file is part of the CampaignChain package.
#
# (c) CampaignChain, Inc. <info@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

campaignchain_report_analytics_metrics_per_activity_index:
    pattern:  /report/analytics/metricsperactivity/{id}
    defaults: { _controller: CampaignChainReportAnalyticsMetricsPerActivityBundle:Page:index, id: 0 }
    methods:  [GET]

campaignchain_report_analytics_metrics_per_activity_activity:
    pattern:  /report/analytics/metricsperactivity/activity/{id}
    defaults: { _controller: CampaignChainReportAnalyticsMetricsPerActivityBundle:Page:activity, id: 0 }